matrix:
  include:
    # api build
    - language: node_js
      node_js: 13
      os: linux
      dist: bionic
      before_script:
        - cd api
      script:
        - npm install && npm run test
      git:
        quiet: true
      env:
        global:
          secure: 'aMV1Bp4meKN0masQWlFtaqUnnNRaoRCEGIqcI5PGWhJWAYDe/HwhR/QGYvbNhYNzhKGxWsEwGx56cuCbL2YcTjr5owFi0CHS3gOmvZbEfVRDmgNO4hHK58k4ZpRX2pXUlcn9S8Mng1YHwYR57FKFYIj3K4n7L/RmVwR8kWWlTVeg9+z2lb6NO8z42jpQhN4zkhZ+LkbBu2FeeGAW+LvjtEX2BnGnnAeOmpHC+BUkiwnXWzmF8mNO5ICt6KI8azYXrHFWSbJhcA2D93o7m03T0OnLOqr3Y6Fq4J6jWDUPtqWTDtTno77jRy0XUYpVPwnJ0mLlJgToCiqTMNm9WTs3E9ghrSRj+g7NX1hwp/zVoyLWOXtpC+NYU4nfT7Xf5AXAaAUvZS5bd5Rb0FH/z55CMGGoKuqHqVbBXfgngS288B04HoYaT3PdNxUs9y8FKiP4/gQaQAQKYGFP54hFxuMxKn1Noj3rLa31kiLoKN7X+teJ0PYOacq0kUwc7ZV4kl4s+2nvytwUJMwsAYf5HwwzKYljp4xJp04qvxxq2LODx7rkGrivRajAudZQOfMNJfuOAFtpBytvwIPEN+b0xP+F53QEC89yPJkfhGljixjSxdFvv8wIXnoezQJpUa7a3wicagaMnOZvP5XUM9pFs0cJ/3HBYR5jUXZS2lXB2Y0wbeA='
    # mobile build
    # - language: node_js
    #   node_js: 13
    #   os: linux
    #   dist: bionic
    #   before_script:
    #     - cd mobile
    #   script:
    #     - npm install && npm run test
    #   git:
    #     quiet: true
    # here will be another build for mobile
