matrix:
  include:
    - language: node_js
      node_js: 13
      os: linux
      dist: bionic
      before_script:
        - cd api
      script:
        - npm install && npm run test
      git:
        quiet: true
      env:
        secure: 'bQ1uns0zrR3QVVr6HsuTQMz7eQBFHoRhqtFkbNIpnXCrHOMiNQmZ3RRgw8oWcysO0NK8ZiRJyxOwJjAhj9Ru9VfHjkNxAvDIc+mXS0MEaXcg1MrYYpiM1j/p3auTmnmlOruTjI237PMYBlrfRgQ/qYHHKyLwls843xzhkFxhRF/m1NSyH9hZldoJaznfCkRip0TMUSzcnrOTybnpyatjN3zuei+mtxzTaKXNNk5iCPmqZRdhMk7R8mkuNhBAoJqwSF7wvvUzsv7yKFQJKiN8tArTfef2ekaiaRxK7X4wjYuwM6IJ+PdF6KFb4dfDheKLEfowFDYftoxzFObyAeC7VAW7BpzmGj3Sw8nlEHZpsdnXa+qQw+n8Sw8KmKidZu9exZuZ+qie7AuHS5YzXeRSGOamC6kPphyJLTL0Tk5ZpzSu5WNGT6wVvAApvYEUcQ2w1MMaXAbXFeRzcq9bq20QVIeAWI57o3n+QAHA4TLrN/OHBc7vW6KzJvmuwij4ZwhH7sMhP8gpRJV0ZtAjjgOTPWIOl3EVyYOdcF29acgVEV3DsyOWGKBH+lrkVICmriGYtTbxRp5X7J6QS3vgwGduSaMtbjcC2Zj6+iuIqaPnMSIDPw3ThZr9ah/juTLa5BNrPBLHrLUj/iJfLZBbrD+wU8bvihyItpIuqmAaeF+QEvw='
