matrix:
  include:
    - language: node_js
      node_js: 13
      os: linux
      dist: bionic
      before_script:
        - cd api
      script:
        - npm install && npm run test
      git:
        quiet: true
