version: '3.1'
services:
  app:
    image: node:latest
    container_name: my-app
    working_dir: /src
    links:
      - mysql
    ports:
      - '3000:3000'
    entrypoint: /src/index.js
    environment:
      'NODE_ENV': 'development'

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      'MYSQL_DATABASE': 'master'
      'MYSQL_ROOT_PASSWORD': '1234'
