services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    command: /home/node/app/node_modules/.bin/nodemon src/index.js
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - ./dbdata:/data/db
    environment:
      'MYSQL_DATABASE': 'master'
      'MYSQL_ROOT_PASSWORD': '1234'
